### ISSUE TITLE
File type glyphs/icons ?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-vim#16]
https://github.com/ryanoasis/vim-devicons

I was looking into this but it feels like a lot of hoops to jump through for not much benefit ...
@samhstn have you used any file type icons in your vim in the past? worth trying?

**Comment by samhstn** [comment]
I have played around with configuring icons in vim in the past - not file icons though

Personally, I don't think there's much benefit from them (that's probably just me though)

**Comment by nelsonic** [comment]
Yeah, my only reasoning for having them was to find files faster by visually recognising the icons.
But I don't think they will make me a better programmer or improve the quality of my code.
So not going to add them. 👍
